Repository URECA-TEAM-5/PopFlix-frontend, pull requests merged in 2024-12, with the labels that each got.

#33 style: WatchList 상세 페이지 퍼블리싱
  package.json
  src/App.jsx
  src/components/watchlist/DetailMovieList.jsx
  src/components/watchlist/DetailOtherStorage.jsx
  src/components/watchlist/DetailStorage.jsx
  src/components/watchlist/WatchListCardItem.jsx
  src/components/watchlist/WatchListDetail.jsx
  src/components/watchlist/WatchListLikeButton.jsx
  src/components/watchlist/WatchListMonth.jsx
  src/components/watchlist/data/allData.js
  src/components/watchlist/data/detailData.js
  src/components/watchlist/data/otherData.js
  src/components/watchlist/modal/NewListModal.jsx
  src/components/watchlist/style/DetailMovieList.js
  src/components/watchlist/style/DetailOtherStorage.js
  src/components/watchlist/style/DetailStorage.js
  src/components/watchlist/style/WatchListAll.js
  src/components/watchlist/style/WatchListDetail.js
  src/components/watchlist/style/WatchListMonth.js
  src/layout/DefaultLayout.jsx
  src/layout/ScrollToTop.jsx
  src/pages/watchlist/WatchListDetailPage.jsx
  src/pages/watchlist/WatchListPage.jsx
  src/pages/watchlist/style/WatchListDetailPage.js
  src/pages/watchlist/style/WatchListPage.js
Labels: fix, style, 은진

#17 style: 회원정보 입력/수정 페이지 UI 제작
  public/assets/camera.svg
  public/assets/google_login_btn.svg
  public/assets/naver_login_btn.svg
  src/components/Login/LoginModal.jsx
  src/components/Login/style/LoginModalStyle.js
  src/components/userInfo/UserInfoGender.jsx
  src/components/userInfo/UserInfoGenre.jsx
  src/components/userInfo/UserInfoImage.jsx
  src/components/userInfo/UserInfoNickname.jsx
  src/components/userInfo/modal/DefaultImageSelectModal.jsx
  src/components/userInfo/modal/ImageSelectModal.jsx
  src/components/userInfo/modal/MyInfoModal.jsx
  src/components/userInfo/modal/WithdrawalModal.jsx
  src/components/userInfo/modal/style/UserInfoModalStyle.js
  src/components/userInfo/style/UserInfoStyle.js
  src/global/globalStyle.js
  src/pages/userInfo/AddUserInfo.jsx
  src/pages/userInfo/UpdateUserInfo.jsx
  src/route/RouteDef.jsx
Labels: style, 지훈

#35 Style: 영화 상세페이지 UI 구현
  public/assets/X.svg
  public/assets/main_banner_black 2.svg
  public/assets/main_banner_black 3.svg
  public/assets/main_banner_black.svg
  public/assets/main_banner_white 2.svg
  public/assets/main_banner_white 3.svg
  public/assets/main_banner_white.svg
  src/api/review/videoReview.js
  src/components/main/MovieList.jsx
  src/components/main/TodayPickMovieList.jsx
  src/components/main/TodayPickMovies.jsx
  src/components/main/WatchListBox.jsx
  src/components/main/data.js
  src/components/main/style/MovieList.module.css
  src/components/main/style/TodayPickMovieList.module.css
  src/components/main/style/TodayPickMovies.module.css
  src/components/main/style/WatchListBox.module.css
  src/components/movieDetail/MovieIntro.jsx
  src/components/movieDetail/PhotoReviewModal.jsx
  src/components/movieDetail/PoppleTip.jsx
  src/components/movieDetail/RatingModal.jsx
  src/components/movieDetail/ShortReview.jsx
  src/components/movieDetail/movieReviewTabs/MovieReviewTabs.jsx
  src/components/movieDetail/movieReviewTabs/PhotoReviewTab.jsx
  src/components/movieDetail/movieReviewTabs/ShortReviewTab.jsx
  src/components/movieDetail/movieReviewTabs/VideoReviewTab.jsx
  src/components/movieDetail/movieReviewTabs/style/MovieReviewTabs.js
  src/components/movieDetail/movieReviewTabs/style/PhotoReviewTab.js
  src/components/movieDetail/movieReviewTabs/style/ShortReviewTab.js
  src/components/movieDetail/movieReviewTabs/style/VideoReviewTab.js
  src/components/movieDetail/style/MovieIntro.js
  src/components/movieDetail/style/MovieReviewTabs.js
  src/components/movieDetail/style/PhotoReviewModal.js
  src/components/movieDetail/style/PoppleTip.js
  src/components/movieDetail/style/ShortReview.js
  src/global/globalStyle.js
  src/pages/main/MainPage.jsx
  src/pages/main/MainPage.module.css
  src/pages/movie/MovieDetailPage.jsx
  src/route/RouteDef.jsx
  src/stores/review/videoReviewStore.js
Labels: style, 성현

#38 refactor: Watchlist 상세페이지 수정 추가
  src/api/mypage/myWatchList.js
  src/api/watchlist/watchlist.js
  src/components/mypage/MyFavoriteWatchList.jsx
  src/components/mypage/MyWatchList.jsx
  src/components/mypage/data/myFavoriteStorage.js
  src/components/mypage/data/myStorage.js
  src/components/mypage/style/MyFavoriteWatchList.js
  src/components/mypage/style/MyWatchList.js
  src/components/watchlist/DetailMovieList.jsx
  src/components/watchlist/DetailOtherStorage.jsx
  src/components/watchlist/DetailStorage.jsx
  src/components/watchlist/EditMovieList.jsx
  src/components/watchlist/EditStorage.jsx
  src/components/watchlist/WatchListAll.jsx
  src/components/watchlist/WatchListDetail.jsx
  src/components/watchlist/WatchListLikeButton.jsx
  src/components/watchlist/WatchListMonth.jsx
  src/components/watchlist/data/detailData.js
  src/components/watchlist/modal/NewFolderCount.jsx
  src/components/watchlist/modal/NewFolderInput.jsx
  src/components/watchlist/modal/NewFolderModal.jsx
  src/components/watchlist/modal/SearchMovieModal.jsx
  src/components/watchlist/modal/style/NewFolderModal.js
  src/components/watchlist/modal/style/SearchMovieModal.js
  src/components/watchlist/style/DetailMovieList.js
  src/components/watchlist/style/DetailOtherStorage.js
  src/components/watchlist/style/DetailStorage.js
  src/components/watchlist/style/EditMoviList.js
  src/components/watchlist/style/EditStorage.js
  src/components/watchlist/style/WatchListAll.js
  src/components/watchlist/style/WatchListMonth.js
  src/pages/mypage/Mypage.jsx
  src/pages/watchlist/WatchListEditPage.jsx
  src/route/RouteDef.jsx
  src/stores/mypage/MyFavoriteWatchListStore.js
  src/stores/mypage/MyWatchListStore.js
  src/stores/watchlist/WatchListStore.js
Labels: refactor, style, 은진

#43 style: MyPage UserProfile 디자인
  src/components/mypage/UserProfile.jsx
  src/pages/mypage/Mypage.jsx
Labels: style, 지훈

#51 fix: 아이콘 경로 수정
  src/components/Login/LoginModal.jsx
  src/components/userInfo/UserInfoImage.jsx
Labels: fix, 지훈

#53 refactor: WatchList 폴더 구조 변경
  src/api/mypage/myWatchList.js
  src/api/watchlistDetail/watchlistDetail.js
  src/components/myWatchlistModal/NewFolderCount.jsx
  src/components/myWatchlistModal/NewFolderInput.jsx
  src/components/myWatchlistModal/NewFolderModal.jsx
  src/components/myWatchlistModal/SearchMovieModal.jsx
  src/components/myWatchlistModal/style/NewFolderModal.js
  src/components/myWatchlistModal/style/SearchMovieModal.js
  src/components/mypage/MyWatchList.jsx
  src/components/watchlistDetail/WatchListDetail.jsx
  src/components/watchlistDetail/WatchListDetailMovieList.jsx
  src/components/watchlistDetail/WatchListDetailOtherStorage.jsx
  src/components/watchlistDetail/WatchListDetailStorage.jsx
  src/components/watchlistDetail/data/detailData.js
  src/components/watchlistDetail/data/otherData.js
  src/components/watchlistDetail/style/WatchListDetailMovieList.js
  src/components/watchlistDetail/style/WatchListDetailOtherStorage.js
  src/components/watchlistDetail/style/WatchListDetailStorage.js
  src/components/watchlistEdit/EditMovieList.jsx
  src/components/watchlistEdit/EditStorage.jsx
  src/components/watchlistEdit/style/EditMoviList.js
  src/components/watchlistEdit/style/EditStorage.js
  src/pages/watchlist/WatchListDetailPage.jsx
  src/pages/watchlist/WatchListEditPage.jsx
  src/stores/watchlist/WatchListDetailStore.js
Labels: refactor, 은진

#54 feat: 토큰 관리
  src/api/axios.js
Labels: feat, 지훈

#57 feat:회원가입 연동 및 토큰관리 수정
  src/api/auth/auth.js
  src/api/axios.js
  src/components/userInfo/UserInfoGender.jsx
  src/components/userInfo/UserInfoImage.jsx
  src/pages/userInfo/AddUserInfo.jsx
Labels: feat, 지훈

#63 fix: 무비인트로 파일 수정
  src/components/movieDetail/MovieIntro.jsx
Labels: fix, 성현

#64 feat: Watchlist api 연동
  public/assets/loadingPopcorn.gif
  src/api/mypage/myFavoriteWatchList.js
  src/api/mypage/myWatchList.js
  src/api/watchlist/watchlist.js
  src/components/myWatchlistModal/NewFolderModal.jsx
  src/components/mypage/MyFavoriteWatchList.jsx
  src/components/mypage/MyWatchList.jsx
  src/components/mypage/style/MyFavoriteWatchList.js
  src/components/mypage/style/MyWatchList.js
  src/components/suspense/LoadingSpinner.jsx
  src/components/suspense/style/SpinnerStyle.js
  src/components/watchlist/WatchListMonth.jsx
  src/components/watchlistEdit/EditMovieList.jsx
  src/components/watchlistEdit/EditStorage.jsx
  src/components/watchlistEdit/style/EditMoviList.js
  src/components/watchlistEdit/style/EditStorage.js
  src/stores/mypage/MyFavoriteWatchListStore.js
  src/stores/mypage/MyWatchListStore.js
  src/stores/search/useSearch.js
Labels: feat, style, 은진

#65 feat:localSotrage에 데이터 저장 및 로그인 완료 관련 페이지
  src/api/axios.js
  src/components/common/header/HeaderIconSection.jsx
  src/components/userInfo/modal/MyInfoModal.jsx
  src/pages/welcome/Welcome.jsx
  src/route/RouteDef.jsx
Labels: feat, 지훈

#66 refactor: userId 로컬스토리지 사용
  src/api/watchlist/watchlist.js
  src/components/myWatchlistModal/NewFolderModal.jsx
  src/components/mypage/MyFavoriteWatchList.jsx
  src/components/mypage/MyWatchList.jsx
  src/components/watchlistEdit/EditMovieList.jsx
  src/components/watchlistEdit/EditStorage.jsx
Labels: refactor, 은진

#68 style: watchlist 관련 UI 수정
  public/assets/api_error.svg
  src/api/watchlist/watchlist.js
  src/components/mypage/MyFavoriteWatchList.jsx
  src/components/mypage/MyWatchList.jsx
  src/components/mypage/style/MyFavoriteWatchList.js
  src/components/mypage/style/MyWatchList.js
  src/components/watchlist/WatchListAll.jsx
  src/components/watchlist/WatchListCardItem.jsx
  src/components/watchlist/WatchListFilter.jsx
  src/components/watchlist/WatchListMonth.jsx
  src/components/watchlist/style/WatchListAll.js
  src/components/watchlist/style/WatchListMonth.js
  src/components/watchlistEdit/EditStorage.jsx
Labels: style, 은진

#69 fix: 이달의 인기 watchlist api 반영
  src/api/watchlist/watchlist.js
  src/components/watchlist/WatchListMonth.jsx
Labels: fix, 은진

#70 fix: 토큰 관리 welcome 페이지 수정
  src/components/common/header/Header.jsx
  src/components/userInfo/modal/MyInfoModal.jsx
  src/pages/welcome/Welcome.jsx
Labels: fix, feat, 지훈

#71 fix: 로그아웃 기능 수정
  src/components/userInfo/modal/MyInfoModal.jsx
Labels: fix, 지훈

#73 style: monthly top css 및 api 수정
  src/api/mypage/myWatchList.js
  src/components/mypage/MyWatchList.jsx
  src/components/watchlist/WatchListMonth.jsx
  src/components/watchlist/style/WatchListMonth.js
Labels: style, 은진

#74 feat/ 상세 페이지 api 연동 구현중
  src/api/movieDetail/movieDetail.js
  src/components/movieDetail/MovieIntro.jsx
  src/components/movieDetail/PhotoReviewModal.jsx
  src/components/movieDetail/PoppleTip.jsx
  src/components/movieDetail/RatingModal.jsx
  src/components/movieDetail/movieReviewTabs/PhotoReviewTab.jsx
  src/pages/movie/MovieDetailPage.jsx
  src/stores/movieDetail/MovieDetailStore.js
Labels: feat, 성현

#76 feat: 로그인 했을때 사용자 이미지 및 Sotrage 변경
  src/api/axios.js
  src/components/common/header/HeaderIconSection.jsx
  src/components/mypage/UserProfile.jsx
  src/components/userInfo/modal/MyInfoModal.jsx
  src/pages/userInfo/AddUserInfo.jsx
  src/pages/welcome/Welcome.jsx
Labels: fix, feat, 지훈

#78 style: 마이페이지 snackbar 추가
  src/components/mypage/MyWatchList.jsx
  src/components/watchlistEdit/EditStorage.jsx
Labels: style, 은진

#79 feat/ 포토리뷰 작성 api 구현중
  src/api/movieDetail/movieDetail.js
  src/components/movieDetail/PhotoReviewModal.jsx
Labels: feat, 성현

#82 fix:오타수정
  src/components/userInfo/modal/chkUserInfo.js
Labels: fix, 지훈

#85 style: watchlist 공용 컴포넌트 적용 및 수정 페이지 UI 변경
  src/api/mypage/myWatchList.js
  src/components/myWatchlistModal/NewFolderInput.jsx
  src/components/myWatchlistModal/NewFolderModal.jsx
  src/components/mypage/MyFavoriteWatchList.jsx
  src/components/mypage/MyWatchList.jsx
  src/components/mypage/style/MyFavoriteWatchList.js
  src/components/mypage/style/MyWatchList.js
  src/components/watchlist/WatchListMonth.jsx
  src/components/watchlist/style/WatchListMonth.js
  src/components/watchlistEdit/EditMovieList.jsx
  src/components/watchlistEdit/EditStorage.jsx
  src/components/watchlistEdit/style/EditMoviList.js
  src/components/watchlistEdit/style/EditStorage.js
  src/pages/watchlist/style/WatchListPage.js
Labels: refactor, style, 은진

#86 feat:회원정보 수정 및 회원탈퇴 그외 오류 수정
  src/api/auth/auth.js
  src/components/mypage/UserProfile.jsx
  src/components/userInfo/modal/WithdrawalModal.jsx
  src/components/userInfo/style/UserInfoStyle.js
  src/pages/userInfo/AddUserInfo.jsx
  src/pages/userInfo/UpdateUserInfo.jsx
Labels: fix, feat

#88 refactor: 코드 수정 및 정리
  src/api/auth/auth.js
  src/api/axios.js
  src/components/mypage/MyWatchList.jsx
  src/components/mypage/UserProfile.jsx
  src/components/userInfo/UserInfoImage.jsx
  src/components/userInfo/UserInfoNickname.jsx
  src/components/userInfo/modal/DefaultImageSelectModal.jsx
  src/components/userInfo/modal/ImageSelectModal.jsx
  src/components/userInfo/modal/MyInfoModal.jsx
  src/pages/userInfo/AddUserInfo.jsx
  src/pages/userInfo/UpdateUserInfo.jsx
  src/pages/welcome/Welcome.jsx
Labels: fix, refactor, 지훈

#90 delete: 리뷰왕 제거
  src/components/common/header/Header.jsx
Labels: 지훈, delete

#91 delete: 주석 제거
  src/api/auth/auth.js
  src/api/axios.js
  src/components/mypage/UserProfile.jsx
  src/components/userInfo/UserInfoImage.jsx
  src/pages/userInfo/UpdateUserInfo.jsx
  src/pages/welcome/Welcome.jsx
Labels: fix, 지훈, delete

#93 refactor: 메인페이지 UI 수정
  public/assets/movie1.svg
  public/assets/movie2.svg
  public/assets/movie3.svg
  src/api/movieDetail/movieDetail.js
  src/api/movieList/movieList.js
  src/components/main/MovieList.jsx
  src/components/main/TodayPickMovieList.jsx
  src/components/main/WatchListBox.jsx
  src/components/main/data.js
  src/components/main/style/MovieList.module.css
  src/components/main/style/TodayPickMovieList.module.css
  src/components/main/style/TodayPickMovies.module.css
  src/components/main/style/WatchListBox.module.css
  src/components/movieDetail/PhotoReviewModal.jsx
  src/stores/movieDetail/MovieDetailStore.js
Labels: refactor, 성현

#94 feat: Watchlist 상세 조회 api 연동 및 UI 수정
  src/api/watchlistDetail/watchlistDetail.js
  src/components/watchlistDetail/WatchListDetail.jsx
  src/components/watchlistDetail/WatchListDetailMovieList.jsx
  src/components/watchlistDetail/WatchListDetailOtherStorage.jsx
  src/components/watchlistDetail/WatchListDetailStorage.jsx
  src/components/watchlistDetail/style/WatchListDetail.js
  src/components/watchlistDetail/style/WatchListDetailOtherStorage.js
  src/stores/watchlist/WatchListDetailStore.js
Labels: feat, style, 은진

#96 refactor: 경로 이동 빠진거 추가
  src/pages/welcome/Welcome.jsx
Labels: refactor, 지훈

#97 fix: 다른 보관함 목록 UI 수정
  src/components/watchlistDetail/WatchListDetailOtherStorage.jsx
  src/components/watchlistDetail/style/WatchListDetailMovieList.js
  src/components/watchlistDetail/style/WatchListDetailOtherStorage.js
Labels: fix, style, 은진

#98 refactor: 리뷰영상 구현중
  src/api/review/videoReview.js
  src/components/movieDetail/movieReviewTabs/MovieReviewTabs.jsx
  src/components/movieDetail/movieReviewTabs/PhotoReviewTab.jsx
  src/components/movieDetail/movieReviewTabs/VideoReviewTab.jsx
  src/pages/movie/MovieDetailPage.jsx
Labels: refactor, 성현

#100 feat: landingPage 제작
  public/assets/popflix.webm
  src/App.jsx
  src/components/mypage/UserProfile.jsx
  src/pages/landing/landingPage.jsx
  src/route/RouteDef.jsx
Labels: feat, 지훈

#102 fix: Watchlist userId 수정
  src/components/myWatchlistModal/NewFolderModal.jsx
  src/components/mypage/MyFavoriteWatchList.jsx
  src/components/mypage/MyWatchList.jsx
  src/components/watchlistDetail/WatchListDetail.jsx
  src/components/watchlistDetail/WatchListDetailOtherStorage.jsx
  src/components/watchlistDetail/WatchListDetailStorage.jsx
  src/components/watchlistEdit/EditMovieList.jsx
  src/components/watchlistEdit/EditStorage.jsx
Labels: fix, 은진

#104 fix: Snackbar 겹침 현상 수정
  src/components/myWatchlistModal/NewFolderModal.jsx
  src/components/mypage/MyWatchList.jsx
  src/pages/mypage/Mypage.jsx
Labels: fix, style, 은진
